### This jupyter notebook contains contents of the lesson "Indexing"

**Author : Umidjon Sattorov. Machine Learning engineer**

In [7]:
# Importing necessary libraries
import pandas as pd 
import numpy as np

In [9]:
import pandas as pd

data = {
    "id": list(range(10)),
    "name": ["Emma Johnson", "Liam Smith", "Olivia Brown", "Noah Williams", 
             "Ava Jones", "William Garcia", "Sophia Miller", "James Davis", 
             "Isabella Rodriguez", "Benjamin Martinez"],
    "city": ["London", "Tokyo", "Sydney", "Paris", "Dubai", 
             "New York", "Berlin", "Toronto", "Rome", "Cape Town"],
    "age": [34, 42, 28, 31, 26, 45, 29, 38, 36, 55],  # Updated ages
    "gender": ["F", "M", "F", "M", "F", "M", "F", "M", "F", "M"],
    "occupation": ["High School Teacher", "Construction Supervisor", "Graphic Designer", 
                  "Police Officer", "Emergency Nurse", "HVAC Technician", 
                  "Coffee Shop Manager", "Freelance Writer", "Dental Hygienist", "Retail Buyer"],
    "social_status": ["Upper-middle", "Working class", "Middle class", "Lower-middle", 
                     "Middle class", "Working class", "Upper-middle", "Lower-middle", 
                     "Upper-middle", "Upper class"],  # 10 statuses
    "purchased_product": ["Classroom Supplies", "Construction Helmet", "Design Software Subscription",
                         "Police Duty Gear", "First Aid Kit", "Toolset (12-piece)",
                         "Organic Grocery Bundle", "Laptop Backpack", "Teeth Whitening Kit", 
                         "Bulk Office Chairs"]
}

df = pd.DataFrame(data)
df.drop(columns = 'id', inplace = True)
df.head()

,name,city,age,gender,occupation,social_status,purchased_product
0,Emma Johnson,London,34,F,High School Teacher,Upper-middle,Classroom Supplies
1,Liam Smith,Tokyo,42,M,Construction Supervisor,Working class,Construction Helmet
2,Olivia Brown,Sydney,28,F,Graphic Designer,Middle class,Design Software Subscription
3,Noah Williams,Paris,31,M,Police Officer,Lower-middle,Police Duty Gear
4,Ava Jones,Dubai,26,F,Emergency Nurse,Middle class,First Aid Kit

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name               10 non-null     object
 1   city               10 non-null     object
 2   age                10 non-null     int64
 3   gender             10 non-null     object
 4   occupation         10 non-null     object
 5   social_status      10 non-null     object
 6   purchased_product  10 non-null     object
dtypes: int64(1), object(6)
memory usage: 692.0+ bytes

In [16]:
df['gender'] = df['gender'].apply(lambda x : 1 if x == 'F' else 0)
df.head()

,name,city,age,gender,occupation,social_status,purchased_product
0,Emma Johnson,London,34,1,High School Teacher,Upper-middle,Classroom Supplies
1,Liam Smith,Tokyo,42,0,Construction Supervisor,Working class,Construction Helmet
2,Olivia Brown,Sydney,28,1,Graphic Designer,Middle class,Design Software Subscription
3,Noah Williams,Paris,31,0,Police Officer,Lower-middle,Police Duty Gear
4,Ava Jones,Dubai,26,1,Emergency Nurse,Middle class,First Aid Kit

In [17]:
df['year'] = df['age'].apply(lambda z :  2025 - z)
df

,name,city,age,gender,occupation,social_status,purchased_product,year
0,Emma Johnson,London,34,1,High School Teacher,Upper-middle,Classroom Supplies,1991
1,Liam Smith,Tokyo,42,0,Construction Supervisor,Working class,Construction Helmet,1983
2,Olivia Brown,Sydney,28,1,Graphic Designer,Middle class,Design Software Subscription,1997
3,Noah Williams,Paris,31,0,Police Officer,Lower-middle,Police Duty Gear,1994
4,Ava Jones,Dubai,26,1,Emergency Nurse,Middle class,First Aid Kit,1999
5,William Garcia,New York,45,0,HVAC Technician,Working class,Toolset (12-piece),1980
6,Sophia Miller,Berlin,29,1,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle,1996
7,James Davis,Toronto,38,0,Freelance Writer,Lower-middle,Laptop Backpack,1987
8,Isabella Rodriguez,Rome,36,1,Dental Hygienist,Upper-middle,Teeth Whitening Kit,1989
9,Benjamin Martinez,Cape Town,55,0,Retail Buyer,Upper class,Bulk Office Chairs,1970

In [19]:
df['social_status'].value_counts()

social_status
Upper-middle     3
Working class    2
Middle class     2
Lower-middle     2
Upper class      1
Name: count, dtype: int64

In [20]:
df['name'].value_counts()

name
Emma Johnson          1
Liam Smith            1
Olivia Brown          1
Noah Williams         1
Ava Jones             1
William Garcia        1
Sophia Miller         1
James Davis           1
Isabella Rodriguez    1
Benjamin Martinez     1
Name: count, dtype: int64

In [23]:
df['occupation'].value_counts()

occupation
High School Teacher        1
Construction Supervisor    1
Graphic Designer           1
Police Officer             1
Emergency Nurse            1
HVAC Technician            1
Coffee Shop Manager        1
Freelance Writer           1
Dental Hygienist           1
Retail Buyer               1
Name: count, dtype: int64

In [22]:
df['age'].value_counts()

age
34    1
42    1
28    1
31    1
26    1
45    1
29    1
38    1
36    1
55    1
Name: count, dtype: int64

In [24]:
df['gender'].value_counts()

gender
1    5
0    5
Name: count, dtype: int64

In [25]:
df[df['social_status'] == "Upper class"]

,name,city,age,gender,occupation,social_status,purchased_product,year
9,Benjamin Martinez,Cape Town,55,0,Retail Buyer,Upper class,Bulk Office Chairs,1970

In [30]:
df.sort_values(by = 'age', ascending = False, inplace = True)

In [33]:
df.sort_index(inplace = True)

In [34]:
df

,name,city,age,gender,occupation,social_status,purchased_product,year
0,Emma Johnson,London,34,1,High School Teacher,Upper-middle,Classroom Supplies,1991
1,Liam Smith,Tokyo,42,0,Construction Supervisor,Working class,Construction Helmet,1983
2,Olivia Brown,Sydney,28,1,Graphic Designer,Middle class,Design Software Subscription,1997
3,Noah Williams,Paris,31,0,Police Officer,Lower-middle,Police Duty Gear,1994
4,Ava Jones,Dubai,26,1,Emergency Nurse,Middle class,First Aid Kit,1999
5,William Garcia,New York,45,0,HVAC Technician,Working class,Toolset (12-piece),1980
6,Sophia Miller,Berlin,29,1,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle,1996
7,James Davis,Toronto,38,0,Freelance Writer,Lower-middle,Laptop Backpack,1987
8,Isabella Rodriguez,Rome,36,1,Dental Hygienist,Upper-middle,Teeth Whitening Kit,1989
9,Benjamin Martinez,Cape Town,55,0,Retail Buyer,Upper class,Bulk Office Chairs,1970

In [10]:
data = {
    "id": list(range(10, 20)),
    "name": ["Sophie Chen", "Mohammed Al-Farsi", "Priya Patel", "Juan Rodriguez", 
             "Yuki Tanaka", "Fatima Zahra", "David Kim", "Amina Diop", 
             "Carlos Silva", "Anya Petrova"],
    "city": ["Singapore", "Cairo", "Mumbai", "Mexico City", 
             "Osaka", "Casablanca", "Seoul", "Dakar", 
             "Rio de Janeiro", "St. Petersburg"],
    "age": [29, 41, 27, 33, 22, 38, 45, 31, 50, 26],
    "gender": ["F", "M", "F", "M", "F", "F", "M", "F", "M", "F"],
    "occupation": ["Data Scientist", "Architect", "Pharmacist", "Journalist", 
                  "Fashion Designer", "Bank Manager", "University Professor", "NGO Director", 
                  "Restaurant Owner", "Ballet Dancer"],
    "social_status": ["Upper-middle", "Upper-middle", "Middle class", "Lower-middle", 
                     "Middle class", "Upper class", "Upper class", "Upper-middle", 
                     "Middle class", "Lower-middle"],
    "education_level": ["Master's", "Bachelor's", "Doctorate", "Bachelor's", 
                       "Associate Degree", "MBA", "PhD", "Master's", 
                       "High School", "Bachelor's"],  # New feature
    "purchased_product": ["Wireless Earbuds", "3D Printer", "Medical Encyclopedia", "Digital Recorder", 
                         "Fabric Samples", "Gold Watch", "Research Tablet", "Charity Event Tickets", 
                         "Commercial Blender", "Dance Shoes"]
}

df_new = pd.DataFrame(data)
df_new.drop(columns = 'id', inplace = True)
df_new.head(10)

,name,city,age,gender,occupation,social_status,education_level,purchased_product
0,Sophie Chen,Singapore,29,F,Data Scientist,Upper-middle,Master's,Wireless Earbuds
1,Mohammed Al-Farsi,Cairo,41,M,Architect,Upper-middle,Bachelor's,3D Printer
2,Priya Patel,Mumbai,27,F,Pharmacist,Middle class,Doctorate,Medical Encyclopedia
3,Juan Rodriguez,Mexico City,33,M,Journalist,Lower-middle,Bachelor's,Digital Recorder
4,Yuki Tanaka,Osaka,22,F,Fashion Designer,Middle class,Associate Degree,Fabric Samples
5,Fatima Zahra,Casablanca,38,F,Bank Manager,Upper class,MBA,Gold Watch
6,David Kim,Seoul,45,M,University Professor,Upper class,PhD,Research Tablet
7,Amina Diop,Dakar,31,F,NGO Director,Upper-middle,Master's,Charity Event Tickets
8,Carlos Silva,Rio de Janeiro,50,M,Restaurant Owner,Middle class,High School,Commercial Blender
9,Anya Petrova,St. Petersburg,26,F,Ballet Dancer,Lower-middle,Bachelor's,Dance Shoes

**Ikkita dataframeni qo'shish**

In [15]:
df_full = pd.concat([df, df_new])
df_full

,name,city,age,gender,occupation,social_status,purchased_product,education_level
0,Emma Johnson,London,34,F,High School Teacher,Upper-middle,Classroom Supplies,NaN
1,Liam Smith,Tokyo,42,M,Construction Supervisor,Working class,Construction Helmet,NaN
2,Olivia Brown,Sydney,28,F,Graphic Designer,Middle class,Design Software Subscription,NaN
3,Noah Williams,Paris,31,M,Police Officer,Lower-middle,Police Duty Gear,NaN
4,Ava Jones,Dubai,26,F,Emergency Nurse,Middle class,First Aid Kit,NaN
5,William Garcia,New York,45,M,HVAC Technician,Working class,Toolset (12-piece),NaN
6,Sophia Miller,Berlin,29,F,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle,NaN
7,James Davis,Toronto,38,M,Freelance Writer,Lower-middle,Laptop Backpack,NaN
8,Isabella Rodriguez,Rome,36,F,Dental Hygienist,Upper-middle,Teeth Whitening Kit,NaN
9,Benjamin Martinez,Cape Town,55,M,Retail Buyer,Upper class,Bulk Office Chairs,NaN
0,Sophie Chen,Singapore,29,F,Data Scientist,Upper-middle,Wireless Earbuds,Master's
1,Mohammed Al-Farsi,Cairo,41,M,Architect,Upper-middle,3D Printer,Bachelor's
2,Priya Patel,Mumbai,27,F,Pharmacist,Middle class,Medical Encyclopedia,Doctorate
3,Juan Rodriguez,Mexico City,33,M,Journalist,Lower-middle,Digital Recorder,Bachelor's
4,Yuki Tanaka,Osaka,22,F,Fashion Designer,Middle class,Fabric Samples,Associate Degree
5,Fatima Zahra,Casablanca,38,F,Bank Manager,Upper class,Gold Watch,MBA
6,David Kim,Seoul,45,M,University Professor,Upper class,Research Tablet,PhD
7,Amina Diop,Dakar,31,F,NGO Director,Upper-middle,Charity Event Tickets,Master's
8,Carlos Silva,Rio de Janeiro,50,M,Restaurant Owner,Middle class,Commercial Blender,High School
9,Anya Petrova,St. Petersburg,26,F,Ballet Dancer,Lower-middle,Dance Shoes,Bachelor's

In [13]:
df_full.reset_index(inplace = True)
df_full

,index,name,city,age,gender,occupation,social_status,purchased_product,education_level
0,0,Emma Johnson,London,34,F,High School Teacher,Upper-middle,Classroom Supplies,NaN
1,1,Liam Smith,Tokyo,42,M,Construction Supervisor,Working class,Construction Helmet,NaN
2,2,Olivia Brown,Sydney,28,F,Graphic Designer,Middle class,Design Software Subscription,NaN
3,3,Noah Williams,Paris,31,M,Police Officer,Lower-middle,Police Duty Gear,NaN
4,4,Ava Jones,Dubai,26,F,Emergency Nurse,Middle class,First Aid Kit,NaN
5,5,William Garcia,New York,45,M,HVAC Technician,Working class,Toolset (12-piece),NaN
6,6,Sophia Miller,Berlin,29,F,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle,NaN
7,7,James Davis,Toronto,38,M,Freelance Writer,Lower-middle,Laptop Backpack,NaN
8,8,Isabella Rodriguez,Rome,36,F,Dental Hygienist,Upper-middle,Teeth Whitening Kit,NaN
9,9,Benjamin Martinez,Cape Town,55,M,Retail Buyer,Upper class,Bulk Office Chairs,NaN
10,0,Sophie Chen,Singapore,29,F,Data Scientist,Upper-middle,Wireless Earbuds,Master's
11,1,Mohammed Al-Farsi,Cairo,41,M,Architect,Upper-middle,3D Printer,Bachelor's
12,2,Priya Patel,Mumbai,27,F,Pharmacist,Middle class,Medical Encyclopedia,Doctorate
13,3,Juan Rodriguez,Mexico City,33,M,Journalist,Lower-middle,Digital Recorder,Bachelor's
14,4,Yuki Tanaka,Osaka,22,F,Fashion Designer,Middle class,Fabric Samples,Associate Degree
15,5,Fatima Zahra,Casablanca,38,F,Bank Manager,Upper class,Gold Watch,MBA
16,6,David Kim,Seoul,45,M,University Professor,Upper class,Research Tablet,PhD
17,7,Amina Diop,Dakar,31,F,NGO Director,Upper-middle,Charity Event Tickets,Master's
18,8,Carlos Silva,Rio de Janeiro,50,M,Restaurant Owner,Middle class,Commercial Blender,High School
19,9,Anya Petrova,St. Petersburg,26,F,Ballet Dancer,Lower-middle,Dance Shoes,Bachelor's

In [14]:
df_full.drop(labels = 'education_level',axis = 1, inplace = True)

df_full.drop(labels = 'year', axis = 1, inplace = True)

KeyError: "['year'] not found in axis"

In [56]:
df_full

,name,city,age,gender,occupation,social_status,purchased_product
0,Emma Johnson,London,34,1,High School Teacher,Upper-middle,Classroom Supplies
1,Liam Smith,Tokyo,42,0,Construction Supervisor,Working class,Construction Helmet
2,Olivia Brown,Sydney,28,1,Graphic Designer,Middle class,Design Software Subscription
3,Noah Williams,Paris,31,0,Police Officer,Lower-middle,Police Duty Gear
4,Ava Jones,Dubai,26,1,Emergency Nurse,Middle class,First Aid Kit
5,William Garcia,New York,45,0,HVAC Technician,Working class,Toolset (12-piece)
6,Sophia Miller,Berlin,29,1,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle
7,James Davis,Toronto,38,0,Freelance Writer,Lower-middle,Laptop Backpack
8,Isabella Rodriguez,Rome,36,1,Dental Hygienist,Upper-middle,Teeth Whitening Kit
9,Benjamin Martinez,Cape Town,55,0,Retail Buyer,Upper class,Bulk Office Chairs
10,Sophie Chen,Singapore,29,F,Data Scientist,Upper-middle,Wireless Earbuds
11,Mohammed Al-Farsi,Cairo,41,M,Architect,Upper-middle,3D Printer
12,Priya Patel,Mumbai,27,F,Pharmacist,Middle class,Medical Encyclopedia
13,Juan Rodriguez,Mexico City,33,M,Journalist,Lower-middle,Digital Recorder
14,Yuki Tanaka,Osaka,22,F,Fashion Designer,Middle class,Fabric Samples
15,Fatima Zahra,Casablanca,38,F,Bank Manager,Upper class,Gold Watch
16,David Kim,Seoul,45,M,University Professor,Upper class,Research Tablet
17,Amina Diop,Dakar,31,F,NGO Director,Upper-middle,Charity Event Tickets
18,Carlos Silva,Rio de Janeiro,50,M,Restaurant Owner,Middle class,Commercial Blender
19,Anya Petrova,St. Petersburg,26,F,Ballet Dancer,Lower-middle,Dance Shoes

In [41]:
df_full.drop(labels = 'index', axis = 1, inplace = True)
df_full

,name,city,age,gender,occupation,social_status,purchased_product,year,education_level
0,Emma Johnson,London,34,1,High School Teacher,Upper-middle,Classroom Supplies,1991.0,NaN
1,Liam Smith,Tokyo,42,0,Construction Supervisor,Working class,Construction Helmet,1983.0,NaN
2,Olivia Brown,Sydney,28,1,Graphic Designer,Middle class,Design Software Subscription,1997.0,NaN
3,Noah Williams,Paris,31,0,Police Officer,Lower-middle,Police Duty Gear,1994.0,NaN
4,Ava Jones,Dubai,26,1,Emergency Nurse,Middle class,First Aid Kit,1999.0,NaN
5,William Garcia,New York,45,0,HVAC Technician,Working class,Toolset (12-piece),1980.0,NaN
6,Sophia Miller,Berlin,29,1,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle,1996.0,NaN
7,James Davis,Toronto,38,0,Freelance Writer,Lower-middle,Laptop Backpack,1987.0,NaN
8,Isabella Rodriguez,Rome,36,1,Dental Hygienist,Upper-middle,Teeth Whitening Kit,1989.0,NaN
9,Benjamin Martinez,Cape Town,55,0,Retail Buyer,Upper class,Bulk Office Chairs,1970.0,NaN
10,Sophie Chen,Singapore,29,F,Data Scientist,Upper-middle,Wireless Earbuds,NaN,Master's
11,Mohammed Al-Farsi,Cairo,41,M,Architect,Upper-middle,3D Printer,NaN,Bachelor's
12,Priya Patel,Mumbai,27,F,Pharmacist,Middle class,Medical Encyclopedia,NaN,Doctorate
13,Juan Rodriguez,Mexico City,33,M,Journalist,Lower-middle,Digital Recorder,NaN,Bachelor's
14,Yuki Tanaka,Osaka,22,F,Fashion Designer,Middle class,Fabric Samples,NaN,Associate Degree
15,Fatima Zahra,Casablanca,38,F,Bank Manager,Upper class,Gold Watch,NaN,MBA
16,David Kim,Seoul,45,M,University Professor,Upper class,Research Tablet,NaN,PhD
17,Amina Diop,Dakar,31,F,NGO Director,Upper-middle,Charity Event Tickets,NaN,Master's
18,Carlos Silva,Rio de Janeiro,50,M,Restaurant Owner,Middle class,Commercial Blender,NaN,High School
19,Anya Petrova,St. Petersburg,26,F,Ballet Dancer,Lower-middle,Dance Shoes,NaN,Bachelor's

**Ma'lumotlar borligini tekshirish**

In [17]:
df_full.isna().sum()

name                  0
city                  0
age                   0
gender                0
occupation            0
social_status         0
purchased_product     0
education_level      10
dtype: int64

In [19]:
df['city'].isin(checking_list)

id
0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8     True
9    False
Name: city, dtype: bool

**Ma'lumotlarni qatorlar bo'yicha o'qish**

*loc[]*

In [22]:
df.iloc[4]

name                       Ava Jones
city                           Dubai
age                               26
gender                             F
occupation           Emergency Nurse
social_status           Middle class
purchased_product      First Aid Kit
Name: 4, dtype: object

In [23]:
# Qisman o'qish
df.iloc[5 : 9]

,name,city,age,gender,occupation,social_status,purchased_product
id,,,,,,,
5,William Garcia,New York,45,M,HVAC Technician,Working class,Toolset (12-piece)
6,Sophia Miller,Berlin,29,F,Coffee Shop Manager,Upper-middle,Organic Grocery Bundle
7,James Davis,Toronto,38,M,Freelance Writer,Lower-middle,Laptop Backpack
8,Isabella Rodriguez,Rome,36,F,Dental Hygienist,Upper-middle,Teeth Whitening Kit

In [ ]:
df.iloc[ : 9]
df.iloc[5 : ]

*loc[]*

In [24]:
temp_df = df.copy()
temp_df.head()

,name,city,age,gender,occupation,social_status,purchased_product
id,,,,,,,
0,Emma Johnson,London,34,F,High School Teacher,Upper-middle,Classroom Supplies
1,Liam Smith,Tokyo,42,M,Construction Supervisor,Working class,Construction Helmet
2,Olivia Brown,Sydney,28,F,Graphic Designer,Middle class,Design Software Subscription
3,Noah Williams,Paris,31,M,Police Officer,Lower-middle,Police Duty Gear
4,Ava Jones,Dubai,26,F,Emergency Nurse,Middle class,First Aid Kit

In [25]:
temp_df.index = temp_df['name']
temp_df.drop(columns = 'name', inplace = True)
temp_df.head()

,city,age,gender,occupation,social_status,purchased_product
name,,,,,,
Emma Johnson,London,34,F,High School Teacher,Upper-middle,Classroom Supplies
Liam Smith,Tokyo,42,M,Construction Supervisor,Working class,Construction Helmet
Olivia Brown,Sydney,28,F,Graphic Designer,Middle class,Design Software Subscription
Noah Williams,Paris,31,M,Police Officer,Lower-middle,Police Duty Gear
Ava Jones,Dubai,26,F,Emergency Nurse,Middle class,First Aid Kit

In [27]:
temp_df.loc[6]

KeyError: 6

In [28]:
temp_df.loc["Olivia Brown"]

city                                       Sydney
age                                            28
gender                                          F
occupation                       Graphic Designer
social_status                        Middle class
purchased_product    Design Software Subscription
Name: Olivia Brown, dtype: object